table _Calculations
	lineageTag: 89f5e92a-d745-49ca-a20d-d1985e589d03

	measure 'Total Runs' = SUM(fact_bating_summary[runs])
		formatString: 0
		displayFolder: Batting
		lineageTag: d0e3b399-448b-469f-b923-80e307033b34

	measure 'Total Innings Batted' = COUNT(fact_bating_summary[match_id])
		formatString: 0
		displayFolder: Batting
		lineageTag: 0b8223cf-74d1-4da1-a14d-ed02494cb254

	measure 'Total Innings Dismissed' = SUM(fact_bating_summary[out])
		formatString: 0
		displayFolder: Batting
		lineageTag: e21b76d3-9067-4f75-859c-af296620de56

	measure 'Batting Avg' = DIVIDE([Total Runs],[Total Innings Dismissed],0)
		displayFolder: Batting
		lineageTag: 8f93b3bc-49db-4fed-9418-c02a4de3f7b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Balls Faced' = SUM(fact_bating_summary[balls])
		formatString: 0
		displayFolder: Batting
		lineageTag: 1ace557c-29a7-4077-870d-ceb0283f670c

	measure 'Strike rate' = ```
			DIVIDE([Total Runs],[Total Balls Faced],0)*100 
			```
		displayFolder: Batting
		lineageTag: e6a31a18-8732-41af-afb2-dd2ad66af3f7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Battling Position' = ROUNDUP(AVERAGE(fact_bating_summary[battingPos]), 0)
		formatString: 0
		displayFolder: Batting
		lineageTag: 1adec08c-ca30-4c48-a2e0-407ad158889e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Boundary %' = DIVIDE(SUM(fact_bating_summary[boundary runs]),[Total Runs],0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Batting
		lineageTag: f8d38ef6-f5fe-4802-9858-728a48c988d0

	measure 'Avg. Balls Faced' = AVERAGE(fact_bating_summary[balls])
		displayFolder: Batting
		lineageTag: 7d055da3-2e3e-4175-ad8d-82212f55bffa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Wickets = SUM(fact_bowling_summary[wickets])
		formatString: 0
		displayFolder: Bowling
		lineageTag: c65a48f9-aacb-4d0a-aaff-4368859831ca

	measure 'Balls Bowled' = SUM(fact_bowling_summary[balls])
		formatString: 0
		displayFolder: Bowling
		lineageTag: 2385f99d-ce4e-4d69-a506-ca8fbd9ea75f

	measure 'Runs Conceded' = SUM(fact_bowling_summary[runs])
		formatString: 0
		displayFolder: Bowling
		lineageTag: 15d7e60a-b6b9-4423-8bce-667b04faf9dc

	measure 'Bowling Economy' = DIVIDE([Runs Conceded],([Balls Bowled]/6), 0)
		displayFolder: Bowling
		lineageTag: 79b52068-9938-4840-8fdc-9bf4e4b05de8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bowling Strike Rate' = DIVIDE([Balls Bowled],[Wickets],0)
		displayFolder: Bowling
		lineageTag: 42c724af-67f2-48ad-860b-9abecb75c739

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bowling Average' = DIVIDE([Runs Conceded], [Wickets], 0)
		displayFolder: Bowling
		lineageTag: d3588c04-8e71-4b97-aea9-a8e94b1b47fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Innings Bowled' = DISTINCTCOUNT(fact_bowling_summary[match_id])
		formatString: 0
		displayFolder: Bowling
		lineageTag: 81f8d752-584e-448d-82b8-73c415d06a29

	measure 'Dot Balls %' = DIVIDE(SUM(fact_bowling_summary[zeros]), SUM(fact_bowling_summary[balls]), 0)
		displayFolder: Bowling
		lineageTag: 889e8787-2e87-4509-ae01-8a5973997722

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Player Selection' = if(ISFILTERED(dim_players[name]),"1", "0")
		displayFolder: Others
		lineageTag: a8d22127-08e8-4393-92df-083d5ca794ec

	measure 'Display Text' = ```
			
			IF(
			    [Player Selection] = "1", 
			    "", 
			    "Select Player(s) by clicking the player's name to see their individual or combined strength."
			)
			
			```
		displayFolder: Others
		lineageTag: c94bdb23-7949-4dde-9026-080cd7c5acca

	measure 'Color Callout Value' = ```
			if([Player Selection]="0", "#D0CF1D","#1D1D2E")
			
			```
		displayFolder: Others
		lineageTag: c3fdace9-46dd-4d05-9c94-2144ff37eee0

	partition _Calculations = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

